name: ManHunt
version: @version@
main: com.github.michaljaz.manhunt.Main
api-version: 1.17
commands:
  compass:
    description: get compass
    usage: /compass
  team:
    description: Join team
    usage: /<command> [hunter,runner,spectator]
  start:
    description: Start manhunt
    usage: /start

