name: ManHunt
version: @version@
main: com.github.michaljaz.manhunt.Main
api-version: 1.16
commands:
  compass:
    description: get compass
    usage: /compass
  team:
    description: Join team
    usage: /<command> [hunter,runner,spectator]

